/* Rich deep-dive content for high-yield elements. Others fall back to a
   computed atom + category overview. Fields: nat, use, ov, bio, sci, eng, cos */
window.PT_DEEP={
"H":{nat:"Most abundant element in the universe (~75% of normal matter).",use:"Fuel, ammonia synthesis, pH.",
 ov:"The simplest atom - one proton, one electron - and the building block from which the stars made everything else.",
 bio:"As the H⁺ ion it sets pH; the hydrogen-ion gradient across the inner mitochondrial membrane is what ATP synthase converts into ATP. Hydrogen bonds hold DNA's strands and fold every protein.",
 sci:"Its single electron gives the cleanest spectral lines in physics (the Balmer series) and made hydrogen the test-bed for quantum theory. Deuterium and tritium are its heavy isotopes.",
 eng:"Hydrogen fuel cells turn H₂ + O₂ into electricity and water; the Haber–Bosch process fixes it into ammonia, feeding roughly half the planet.",
 cos:"Fusion of hydrogen into helium powers the Sun and every main-sequence star - the original energy source behind nearly all life."},
"He":{nat:"Second-most abundant element; on Earth it's collected from natural gas.",use:"Cryogenics, MRI, lift.",
 ov:"A noble gas so unreactive it forms essentially no compounds, and so light it escapes Earth's gravity.",
 bio:"Biologically inert, but breathed in heliox mixes to help patients move air through narrowed airways, and by divers to avoid nitrogen narcosis.",
 sci:"Liquid helium boils at 4.2 K and, below 2.17 K, becomes a frictionless superfluid; it cools the superconducting magnets at the heart of physics.",
 eng:"Indispensable for MRI magnets, semiconductor manufacturing, and leak detection - a finite, non-renewable resource once it's released.",
 cos:"Forged in the Big Bang and in stellar cores; first detected in the Sun's spectrum before it was ever found on Earth."},
"C":{nat:"Natural; the structural backbone of all known life.",use:"Organic chemistry, steel, materials.",
 ov:"The element of life: four bonds, endless architectures - chains, rings, sheets, cages.",
 bio:"Every biomolecule - carbohydrate, lipid, protein, nucleic acid - is a carbon skeleton. The carbon cycle moves it between CO₂, living tissue, and rock.",
 sci:"Its bonding versatility founds all of organic chemistry; radiocarbon (¹⁴C) dating reads the clock of decay; allotropes range from diamond to graphite to graphene.",
 eng:"Carbon fiber and steel (iron + carbon) build the modern world; graphene and nanotubes are the frontier of materials science.",
 cos:"Made in dying stars and seeded across the galaxy - the cosmos is, chemically, a carbon story."},
"N":{nat:"78% of the air you breathe.",use:"Fertilizer, proteins, inert atmospheres.",
 ov:"An atmosphere of it surrounds us, yet life can't use it until it's 'fixed' into a reactive form.",
 bio:"Nitrogen is in every amino acid and nucleotide. Biological nitrogen fixation by bacteria, and industrial fixation by humans, gate how much life a system can support.",
 sci:"The triple bond in N₂ is one of the strongest in chemistry, which is why it's so inert; liquid nitrogen (77 K) is a workhorse coolant.",
 eng:"The Haber–Bosch process converts N₂ to ammonia for fertilizer; nitrogen blankets protect food and electronics from oxidation.",
 cos:"A major product of stellar nucleosynthesis and a key component of many planetary atmospheres."},
"O":{nat:"~21% of air; most abundant element in Earth's crust.",use:"Respiration, combustion, oxides.",
 ov:"The element that made complex life possible - and the one that lets it burn fuel for energy.",
 bio:"The final electron acceptor in cellular respiration; without O₂ at the end of the chain, ATP production collapses. It's carried by hemoglobin's iron.",
 sci:"A potent oxidizer; its discovery overturned the phlogiston theory and founded modern chemistry. Ozone (O₃) shields the surface from UV.",
 eng:"Drives steelmaking, combustion, and medical oxygen; liquid oxygen is a rocket oxidizer.",
 cos:"Built in massive stars; the Great Oxidation Event reshaped Earth's atmosphere ~2.4 billion years ago."},
"F":{nat:"Natural but always combined; the most reactive nonmetal.",use:"Toothpaste, Teflon, etching.",
 ov:"The most electronegative element - it grabs electrons from almost anything.",
 bio:"Trace fluoride hardens tooth enamel into fluorapatite, reducing decay; in excess it's toxic.",
 sci:"So reactive it even attacks glass and was isolated only after decades of dangerous attempts (Moissan, 1886).",
 eng:"Builds PTFE (Teflon), refrigerants, and the etchants and high-κ layers of semiconductor fabrication.",
 cos:"Relatively rare cosmically because stellar processes readily destroy it."},
"Na":{nat:"Natural, always as a salt; abundant in seawater.",use:"Nerve signaling, salt, lamps.",
 ov:"A soft metal so reactive it bursts into flame on water - yet half of table salt.",
 bio:"The Na⁺/K⁺-ATPase pumps sodium out of every cell, setting the gradient that fires neurons and muscle and drives nutrient absorption.",
 sci:"Its bright yellow emission line is a classic flame-test and the glow of street lamps.",
 eng:"Molten sodium cools fast nuclear reactors; sodium-ion batteries are an emerging cheap alternative to lithium.",
 cos:"Forged in stars; its D-lines are among the most studied features in astronomical spectra."},
"Mg":{nat:"Natural; eighth-most abundant element in the crust.",use:"Enzymes, alloys, chlorophyll.",
 ov:"A light structural metal and a quiet workhorse of biochemistry.",
 bio:"A cofactor for hundreds of enzymes - every reaction that uses ATP actually uses Mg·ATP - and the atom at the center of chlorophyll.",
 sci:"Burns with a brilliant white light; a strong reducing agent used to win other metals from their oxides.",
 eng:"Magnesium alloys are among the lightest structural metals, used in aerospace and automotive parts.",
 cos:"A common product of stellar carbon and neon burning."},
"Al":{nat:"Most abundant metal in the crust (as bauxite).",use:"Packaging, aircraft, wiring.",
 ov:"Once more precious than gold, now the everyday light metal - because electricity unlocked it.",
 bio:"No biological role; high exposure is neurotoxic, so the body largely excludes it.",
 sci:"Forms a self-healing oxide layer that resists corrosion; extracted by the energy-hungry Hall–Héroult electrolysis.",
 eng:"Strong-yet-light alloys build aircraft, cars, cans, and power lines; endlessly recyclable for a fraction of the smelting energy.",
 cos:"²⁶Al, a radioactive isotope, heated the earliest planetesimals in the young solar system."},
"Si":{nat:"Second-most abundant crustal element (as silicates).",use:"Chips, glass, solar cells.",
 ov:"The rock beneath our feet and the brain inside our machines.",
 bio:"Trace roles in connective tissue and in the silica skeletons of diatoms and grasses.",
 sci:"A metalloid semiconductor whose conductivity can be precisely tuned by doping - the basis of all modern electronics.",
 eng:"Ultra-pure silicon crystals are sliced into the wafers of every computer chip and most solar panels.",
 cos:"A major rock-forming element across the terrestrial planets."},
"P":{nat:"Natural, always combined (phosphates).",use:"DNA, ATP, fertilizer.",
 ov:"The element of energy and information in the cell.",
 bio:"Phosphate is the backbone of DNA and RNA, the 'currency' bonds of ATP, and the on/off switch of protein phosphorylation; it's also bone mineral.",
 sci:"White phosphorus glows and ignites in air; its discovery (from urine, 1669) was the first by a known person.",
 eng:"Phosphate fertilizer underpins modern agriculture - and is a finite, mined resource.",
 cos:"Comparatively scarce in the cosmos, which makes its central role in biochemistry striking."},
"S":{nat:"Natural; found native near volcanoes.",use:"Proteins, sulfuric acid, vulcanization.",
 ov:"The yellow element of brimstone and of the bonds that hold proteins in shape.",
 bio:"In the amino acids cysteine and methionine; disulfide bridges lock protein and antibody structure; part of several vitamins and cofactors.",
 sci:"Sulfuric acid is the most-produced industrial chemical and a rough index of an economy's output.",
 eng:"Vulcanization with sulfur turns soft rubber into tires; sulfur is central to fertilizers and refining.",
 cos:"Produced in stellar oxygen burning and spread by supernovae."},
"Cl":{nat:"Natural, always combined; abundant in seawater.",use:"Disinfection, salt, PVC.",
 ov:"A poison gas that, tamed as the chloride ion, is essential to life.",
 bio:"The major extracellular anion; balances charge, drives the chloride shift in red cells, and is secreted as stomach acid (HCl).",
 sci:"A strong oxidizer and the classic example of an electronegative halogen forming ionic salts with metals.",
 eng:"Chlorination made drinking water safe - a public-health milestone; it also makes PVC and countless solvents.",
 cos:"Forged in stars; detected in interstellar clouds as HCl and other molecules."},
"K":{nat:"Natural; seventh-most abundant crustal element.",use:"Nerve signaling, fertilizer.",
 ov:"The dominant ion inside your cells, and the counterpart to sodium in every nerve impulse.",
 bio:"The main intracellular cation; the K⁺ gradient sets the resting membrane potential, and its efflux repolarizes neurons and the heart. Potassium swings are acutely cardiac-dangerous.",
 sci:"A soft, violently water-reactive alkali metal with a lilac flame; ⁴⁰K is a natural radioactive clock for dating rocks.",
 eng:"Potash is one of the three primary fertilizer nutrients (the 'K' in N-P-K).",
 cos:"Made in stars; ⁴⁰K contributes to Earth's internal radioactive heat."},
"Ca":{nat:"Natural; fifth-most abundant crustal element.",use:"Bone, signaling, cement.",
 ov:"Structure and signal at once - it builds the skeleton and triggers the cell.",
 bio:"Hydroxyapatite gives bone and teeth their hardness; as a tightly controlled second messenger, Ca²⁺ triggers muscle contraction, neurotransmitter release, and clotting.",
 sci:"A reactive alkaline-earth metal; its carbonate (limestone) and sulfate (gypsum) shape geology and construction.",
 eng:"Limestone and lime are the backbone of cement, steel, and glass making.",
 cos:"A product of stellar oxygen and silicon burning; common in rocky bodies."},
"Fe":{nat:"Natural; most of Earth's core, fourth in the crust.",use:"Steel, hemoglobin, magnets.",
 ov:"The metal that built civilization and the atom that carries your oxygen.",
 bio:"At the center of heme, iron binds O₂ in hemoglobin and shuttles electrons in the respiratory chain; deficiency causes anemia, overload damages organs.",
 sci:"Iron-56 sits near the peak of nuclear binding energy per nucleon, so fusion stops around iron - the endpoint of energy-releasing fusion in stars. It's strongly ferromagnetic.",
 eng:"Iron + carbon = steel, the dominant structural material of the modern world.",
 cos:"The last element a massive star can fuse for energy; its build-up triggers core collapse and supernova."},
"Cu":{nat:"Natural; sometimes found native.",use:"Wiring, enzymes, alloys.",
 ov:"The first metal humans worked, and still the wire that carries our power.",
 bio:"A cofactor in enzymes for energy production and iron handling (e.g., cytochrome c oxidase); deficiency and overload (Wilson's disease) both cause disease.",
 sci:"Second only to silver in electrical conductivity; its salts are famously blue-green.",
 eng:"The default conductor for wiring and motors; bronze (Cu+Sn) and brass (Cu+Zn) are foundational alloys.",
 cos:"Synthesized in massive stars and supernovae."},
"Zn":{nat:"Natural, always combined.",use:"Enzymes, galvanizing, immunity.",
 ov:"A quiet but essential trace metal - in hundreds of proteins and on every galvanized surface.",
 bio:"A structural and catalytic cofactor in 300+ enzymes and in 'zinc-finger' DNA-binding proteins; vital for immunity, healing, and taste.",
 sci:"A reactive metal that readily gives up electrons - which is exactly why it protects iron.",
 eng:"Galvanizing coats steel in zinc as a sacrificial anode against rust; the negative electrode of many batteries.",
 cos:"Produced in stars and dispersed by stellar death."},
"I":{nat:"Natural, concentrated in seawater and seaweed.",use:"Thyroid hormone, antiseptic, contrast.",
 ov:"A trace halogen with an outsized job: it runs your metabolism.",
 bio:"The thyroid uses iodine to build T₃ and T₄, the hormones that set metabolic rate; deficiency causes goiter and, in development, cretinism - which iodized salt prevents.",
 sci:"A purple-vapor halogen; its heavy nucleus makes it useful as an X-ray/CT contrast agent.",
 eng:"Iodine disinfectants, and radioactive ¹³¹I to image and treat the thyroid.",
 cos:"A heavy element built largely by neutron capture in stellar and supernova environments."},
"Au":{nat:"Natural; found native as the metal.",use:"Currency, electronics, medicine.",
 ov:"Prized for not changing - the metal that never tarnishes.",
 bio:"Largely inert in the body; gold compounds have been used for rheumatoid arthritis and gold nanoparticles are emerging in diagnostics and targeted therapy.",
 sci:"Extremely unreactive and an excellent conductor; relativistic effects on its electrons give gold its yellow color.",
 eng:"Corrosion-proof contacts and bonding wires in electronics; reflective coatings on spacecraft and visors.",
 cos:"Forged in the most violent events in the universe - neutron-star collisions."},
"Li":{nat:"Natural; from brines and pegmatites.",use:"Mood stabilizer, batteries.",
 ov:"The lightest metal - so light it floats on oil.",
 bio:"Lithium salts are a frontline mood stabilizer for bipolar disorder, with a narrow therapeutic window tracked by blood levels.",
 sci:"The least dense metal and one of the most electropositive; gives a crimson flame.",
 eng:"Lithium-ion batteries power phones, laptops, and electric vehicles.",
 cos:"One of the only elements made (in trace) in the Big Bang itself."},
"Be":{nat:"Natural, in beryl and emerald.",use:"Aerospace alloys, X-ray windows.",
 ov:"Light, extraordinarily stiff - and toxic.",
 bio:"No biological role; inhaled dust causes chronic berylliosis, a granulomatous lung disease.",
 sci:"Low atomic number makes it nearly transparent to X-rays.",
 eng:"Copper-beryllium makes non-sparking tools and springs; used in spacecraft and X-ray windows.",
 cos:"Skipped by stellar fusion; made when cosmic rays shatter heavier nuclei (spallation)."},
"B":{nat:"Natural, as borates.",use:"Glass, detergents, semiconductors.",
 ov:"A metalloid that bridges metals and nonmetals.",
 bio:"Essential for plants; a possible trace role in bone and hormones in animals.",
 sci:"Boron-10 is a powerful neutron absorber.",
 eng:"Borosilicate glass (Pyrex), fiberglass, boron-doped chips, and neutron shielding.",
 cos:"Like lithium and beryllium, made by cosmic-ray spallation, not stellar fusion."},
"Ne":{nat:"Trace in air.",use:"Signs, lasers, cryogenics.",
 ov:"The glow behind 'neon' lights.",
 bio:"Biologically inert.",
 sci:"A noble gas with a brilliant red-orange electrical discharge.",
 eng:"Neon signage, helium-neon lasers, and a deep cryogenic refrigerant.",
 cos:"Common in the universe (made in stellar alpha processes) though rare on Earth."},
"Ar":{nat:"~1% of the air.",use:"Inert shielding, lighting.",
 ov:"The 'lazy' gas - the most abundant noble gas on Earth.",
 bio:"Inert.",
 sci:"Most of Earth's argon is argon-40 from potassium decay, the basis of K-Ar dating.",
 eng:"Shielding gas for welding and an inert fill for bulbs and insulated windows.",
 cos:"Produced in stellar nucleosynthesis; on Earth it builds up from ⁴⁰K decay."},
"Cr":{nat:"Natural, as chromite.",use:"Stainless steel, plating, pigments.",
 ov:"The element of color and corrosion resistance.",
 bio:"Trivalent chromium has a debated role in glucose handling; hexavalent chromium is a carcinogen.",
 sci:"A passivating oxide film is what makes stainless steel stainless; its compounds are vividly colored.",
 eng:"Chrome plating, stainless steel, leather tanning, and pigments.",
 cos:"An iron-peak element from massive stars and supernovae."},
"Mn":{nat:"Natural; abundant ore.",use:"Steel, enzymes, batteries.",
 ov:"A hardener of steel and a quiet enzyme metal.",
 bio:"Cofactor for antioxidant (Mn-SOD) and metabolic enzymes; in excess it is neurotoxic (manganism, Parkinson-like).",
 sci:"Cycles through many oxidation states - KMnO₄ is a classic oxidizer.",
 eng:"Essential in steelmaking and in dry-cell and lithium battery cathodes.",
 cos:"Made in stellar silicon burning."},
"Co":{nat:"Natural.",use:"Vitamin B12, magnets, batteries.",
 ov:"The metal at the core of vitamin B12.",
 bio:"The cobalt atom sits at the center of cobalamin (B12), required for DNA synthesis and nerve myelin; deficiency causes pernicious anemia.",
 sci:"Ferromagnetic; cobalt-60 is a gamma source for radiotherapy and sterilization.",
 eng:"Superalloys, permanent magnets, and lithium-ion cathodes.",
 cos:"Forged in massive stars and supernovae."},
"Ni":{nat:"Natural; much of Earth's core.",use:"Stainless steel, plating, batteries.",
 ov:"A tough, corrosion-resistant metal - and a common allergen.",
 bio:"A trace cofactor in some microbial enzymes (e.g., urease); a frequent contact allergen in jewelry.",
 sci:"Ferromagnetic and resistant to oxidation.",
 eng:"Stainless steel, coins, NiMH and Li-ion batteries, and hydrogenation catalysts.",
 cos:"An iron-peak element; abundant in metallic asteroids and planetary cores."},
"Ga":{nat:"Natural, trace.",use:"Semiconductors, LEDs.",
 ov:"A metal that melts in your hand.",
 bio:"No natural role; gallium is studied in imaging and as an antimicrobial that mimics iron.",
 sci:"Melts at ~30°C; gallium nitride and arsenide are key semiconductors.",
 eng:"GaN drives efficient LEDs and fast chargers; GaAs powers lasers and solar cells.",
 cos:"A rare, dispersed product of stellar nucleosynthesis."},
"Ge":{nat:"Natural, trace.",use:"Optics, semiconductors.",
 ov:"The metalloid that launched the transistor.",
 bio:"No essential role.",
 sci:"A semiconductor used in the first transistors; transparent to infrared light.",
 eng:"Infrared/night-vision optics, fiber-optic dopant, SiGe chips, and solar cells.",
 cos:"Built partly by neutron capture in stars."},
"As":{nat:"Natural; in minerals and groundwater.",use:"Doping, (historically) pesticides, medicine.",
 ov:"The classic poison - and, in trace, a modern cancer drug.",
 bio:"Highly toxic (it mimics phosphate and disrupts ATP); chronic groundwater exposure is a global health crisis, yet arsenic trioxide cures a leukemia (APL).",
 sci:"A metalloid whose phosphate-mimicry underlies both its toxicity and its chemistry.",
 eng:"Semiconductor doping; historically wood preservatives and pigments.",
 cos:"Dispersed in trace amounts by stellar processes."},
"Se":{nat:"Natural, trace; rich in Brazil nuts.",use:"Antioxidant enzymes, electronics.",
 ov:"An essential trace nonmetal with a narrow safe range.",
 bio:"Built into selenocysteine in glutathione peroxidase and thyroid enzymes; both deficiency (Keshan disease) and excess (selenosis) cause harm.",
 sci:"Photoconductive - its resistance drops in light.",
 eng:"Historically photocopier drums and photocells; glass decolorizing and solar cells.",
 cos:"Made by neutron capture in stars."},
"Br":{nat:"Natural; from seawater and brines.",use:"Flame retardants, (historically) sedatives.",
 ov:"One of only two elements that are liquid at room temperature.",
 bio:"Recently shown essential for assembling collagen-IV in basement membranes; bromide was once a sedative and anticonvulsant.",
 sci:"A dense red-brown liquid halogen with choking vapor.",
 eng:"Flame retardants, drilling fluids, and photographic silver bromide.",
 cos:"A heavier halogen from stellar nucleosynthesis."},
"Kr":{nat:"Trace in air.",use:"Lighting, lasers.",
 ov:"A 'hidden' noble gas.",
 bio:"Inert; mildly narcotic only at high pressure.",
 sci:"Its orange-red spectral line once defined the meter.",
 eng:"High-performance lighting, window insulation, and Kr-85 leak detection.",
 cos:"A trace product of stellar nucleosynthesis."},
"Rb":{nat:"Natural, trace.",use:"Atomic clocks, imaging, research.",
 ov:"A soft, hyper-reactive alkali metal.",
 bio:"Loosely follows potassium; rubidium-82 is a PET tracer for heart perfusion.",
 sci:"Used in atomic clocks and in cold-atom and Bose-Einstein-condensate physics.",
 eng:"Specialty glass, photocells, and frequency standards.",
 cos:"Made by neutron capture; ⁸⁷Rb is a slow radioactive dating clock."},
"Sr":{nat:"Natural.",use:"Red fireworks, bone medicine.",
 ov:"Calcium's heavier cousin - it follows calcium into bone.",
 bio:"Strontium has been used for osteoporosis; radioactive Sr-90 from fallout is dangerous precisely because bone absorbs it like calcium.",
 sci:"Gives a brilliant crimson flame.",
 eng:"Red fireworks and flares, ferrite magnets, and specialty glass.",
 cos:"Produced by neutron capture in stars."},
"Zr":{nat:"Natural.",use:"Nuclear cladding, ceramics, implants.",
 ov:"Corrosion-proof and nearly transparent to neutrons.",
 bio:"Biocompatible - used in dental and joint implants.",
 sci:"Very low neutron absorption makes it ideal inside reactors.",
 eng:"Zircaloy fuel-rod cladding, tough zirconia ceramics, and cubic-zirconia gems.",
 cos:"A neutron-capture product."},
"Mo":{nat:"Natural.",use:"Enzymes, high-strength steel.",
 ov:"A refractory metal essential to life's nitrogen and sulfur chemistry.",
 bio:"The molybdopterin cofactor runs enzymes like xanthine oxidase and sulfite oxidase, and bacterial nitrogen fixation.",
 sci:"Extremely high melting point; strengthens steel.",
 eng:"High-temperature alloys, catalysts, electrodes, and the lubricant MoS₂.",
 cos:"A neutron-capture element."},
"Tc":{nat:"Synthetic - the first artificial element.",use:"Medical imaging.",
 ov:"The lightest element with no stable isotope: made, not mined.",
 bio:"Technetium-99m is the workhorse of nuclear medicine, imaging bone, heart, kidneys, and more.",
 sci:"Mendeleev predicted it as 'eka-manganese'; its name means 'artificial'.",
 eng:"Roughly 30 million diagnostic scans a year rely on Tc-99m.",
 cos:"Seen in some stars' spectra - direct evidence that stars are making elements now."},
"Ru":{nat:"Natural, rare.",use:"Electronics, catalysis.",
 ov:"A hard platinum-group metal.",
 bio:"Ruthenium complexes are in development as anticancer agents.",
 sci:"An excellent catalyst; ruthenium dyes drive some solar cells.",
 eng:"Hard-drive coatings, electrical contacts, and catalysis (ammonia, metathesis).",
 cos:"A platinum-group neutron-capture element."},
"Pd":{nat:"Natural, rare.",use:"Catalytic converters, electronics.",
 ov:"A platinum-group metal that soaks up hydrogen like a sponge.",
 bio:"A contact allergen; some palladium complexes are studied medicinally.",
 sci:"Absorbs hundreds of times its volume in hydrogen and powers Nobel-winning cross-coupling reactions.",
 eng:"Catalytic converters, electronics, hydrogen purification, and white-gold jewelry.",
 cos:"A platinum-group element from neutron capture."},
"Ag":{nat:"Natural; found native.",use:"Antimicrobial, electronics, photography.",
 ov:"The best electrical and thermal conductor of all metals.",
 bio:"Silver ions are antimicrobial - used in wound dressings; overuse turns skin blue-grey (argyria).",
 sci:"Highest electrical conductivity of any element; silver halides are light-sensitive (film).",
 eng:"Contacts, solder, solar-cell paste, mirrors, and antimicrobial coatings.",
 cos:"Forged by neutron capture, including in neutron-star mergers."},
"Cd":{nat:"Natural, with zinc ores.",use:"Batteries, pigments (toxic).",
 ov:"A toxic, soft metal that shadows zinc.",
 bio:"A cumulative poison of kidney and bone ('itai-itai' disease); it displaces zinc in enzymes.",
 sci:"Low-melting and a strong neutron absorber.",
 eng:"NiCd batteries, yellow/red pigments, and reactor control rods - use is declining for toxicity.",
 cos:"A neutron-capture product."},
"In":{nat:"Natural, trace.",use:"Touchscreens, solders.",
 ov:"A soft metal behind nearly every touchscreen.",
 bio:"No biological role.",
 sci:"Indium tin oxide (ITO) is both transparent and electrically conductive.",
 eng:"ITO coatings for displays and solar cells, low-temperature solders, and semiconductors.",
 cos:"A rare neutron-capture element."},
"Sn":{nat:"Natural; from cassiterite.",use:"Solder, coatings, bronze.",
 ov:"An ancient metal - half of bronze and the 'tin' can.",
 bio:"Minimal role; inorganic tin is low-toxicity, organotins more so.",
 sci:"It emits a 'tin cry' when bent and crumbles to powder in deep cold ('tin pest').",
 eng:"Electronic solder, tin-plated steel cans, bronze, and float glass.",
 cos:"A neutron-capture element with a record number of stable isotopes."},
"Sb":{nat:"Natural.",use:"Flame retardants, alloys.",
 ov:"A metalloid known since antiquity as kohl eye paint.",
 bio:"Toxic; antimony drugs treat leishmaniasis.",
 sci:"Expands on freezing (like water), which aids fine casting.",
 eng:"Flame retardants (paired with bromine), lead-acid battery alloys, and semiconductors.",
 cos:"A neutron-capture element."},
"Te":{nat:"Natural, rare.",use:"Solar cells, alloys.",
 ov:"A rare metalloid with a garlicky signature.",
 bio:"Toxic; even trace exposure causes garlic breath.",
 sci:"Cadmium telluride is a leading thin-film solar material.",
 eng:"CdTe solar panels, thermoelectrics, machinable steel, and rewritable optical discs.",
 cos:"Built largely by rapid neutron capture."},
"Xe":{nat:"Trace in air.",use:"Lighting, anesthesia, spacecraft thrusters.",
 ov:"A heavy noble gas that actually reacts - and can put you to sleep.",
 bio:"A potent, organ-protective general anesthetic (rarely used due to cost).",
 sci:"Forms genuine compounds (XeF₄ and more), overturning the idea that noble gases never react.",
 eng:"Xenon headlights and camera flashes, and ion thrusters that propel deep-space probes.",
 cos:"Xenon isotopes record the chemistry of the early solar system."},
"Cs":{nat:"Natural.",use:"Atomic clocks (the second), drilling.",
 ov:"The element that defines time.",
 bio:"Follows potassium; radioactive Cs-137 from fallout is a contamination hazard.",
 sci:"The SI second is defined by a cesium-133 transition; it is the most electropositive stable element.",
 eng:"Atomic clocks behind GPS, high-density drilling fluids, and photocells.",
 cos:"Made by neutron capture; Cs-137 is a fission product."},
"Ba":{nat:"Natural.",use:"Medical contrast, drilling, green fireworks.",
 ov:"A heavy metal you might drink for an X-ray.",
 bio:"Insoluble barium sulfate is a safe GI contrast agent; soluble barium salts are toxic.",
 sci:"Dense, with a green flame color.",
 eng:"Drilling mud (barite), green pyrotechnics, and a component of YBCO superconductors.",
 cos:"A neutron-capture element."},
"La":{nat:"Natural rare earth.",use:"Optics, catalysis, batteries.",
 ov:"The element that 'lies hidden' - first of the rare earths.",
 bio:"No natural role; lanthanum carbonate binds phosphate in kidney patients.",
 sci:"Makes high-refractive-index optical glass.",
 eng:"Camera lenses, fluid-cracking catalysts, and NiMH battery alloys.",
 cos:"An s-process neutron-capture element."},
"Ce":{nat:"The most abundant rare earth.",use:"Catalysts, polishing, lighter flints.",
 ov:"The workhorse rare earth.",
 bio:"No biological role.",
 sci:"Switches easily between +3 and +4, letting it store and release oxygen.",
 eng:"Catalytic converters, glass polishing, self-cleaning ovens, and ferrocerium 'flint'.",
 cos:"Produced by neutron capture."},
"Pr":{nat:"Natural rare earth.",use:"Magnets, glass coloring.",
 ov:"A rare earth that strengthens magnets and tints glass.",
 bio:"No natural role.",
 sci:"Added to neodymium magnets; colors glass a clean green.",
 eng:"Aircraft-engine alloys, welder's goggles (it filters glare), and magnets.",
 cos:"An s-process neutron-capture element."},
"Nd":{nat:"Natural rare earth.",use:"The strongest permanent magnets.",
 ov:"The magnet element behind modern motors.",
 bio:"No natural role.",
 sci:"Neodymium-iron-boron magnets are the strongest commercial permanent magnets.",
 eng:"EV and wind-turbine motors, hard drives, headphones, and high-power lasers.",
 cos:"A neutron-capture rare earth."},
"Sm":{nat:"Natural rare earth.",use:"High-temperature magnets, cancer therapy.",
 ov:"A rare earth for magnets that keep their strength when hot.",
 bio:"Samarium-153 treats bone-cancer pain.",
 sci:"Samarium-cobalt magnets resist demagnetization at high temperature.",
 eng:"Aerospace and military magnets, neutron absorption, and catalysis.",
 cos:"A neutron-capture element."},
"Eu":{nat:"Natural rare earth, the scarcest.",use:"Phosphors, anti-counterfeiting.",
 ov:"The rare earth that lights up your screen.",
 bio:"No natural role.",
 sci:"Europium phosphors emit pure red and blue and fluoresce under UV.",
 eng:"Screen and lamp phosphors, and the security marks on euro banknotes.",
 cos:"A neutron-capture element."},
"Gd":{nat:"Natural rare earth.",use:"MRI contrast, neutron shielding.",
 ov:"The rare earth inside the MRI machine.",
 bio:"Chelated gadolinium is the standard MRI contrast agent - its seven unpaired electrons brighten tissues; free Gd is toxic.",
 sci:"Has one of the highest neutron-absorption cross-sections and is magnetic near room temperature.",
 eng:"MRI contrast, reactor shielding, and magnetic-refrigeration research.",
 cos:"A neutron-capture element."},
"Tb":{nat:"Natural rare earth.",use:"Green phosphors, sensors.",
 ov:"A rare earth for green light and shape-changing alloys.",
 bio:"No natural role.",
 sci:"Terbium phosphors glow green; Terfenol-D changes shape in magnetic fields.",
 eng:"Display and lamp phosphors, magnetostrictive sensors and actuators.",
 cos:"A neutron-capture element."},
"Dy":{nat:"Natural rare earth.",use:"Heat-resistant magnets.",
 ov:"'Hard to get' - the rare earth that keeps magnets working when hot.",
 bio:"No natural role.",
 sci:"Added to NdFeB magnets to resist demagnetization at high temperature.",
 eng:"EV and wind-turbine motors, data storage, and dosimeters.",
 cos:"A neutron-capture element."},
"Ho":{nat:"Natural rare earth.",use:"Lasers, strong magnets.",
 ov:"The element with the strongest magnetic moment.",
 bio:"Holmium lasers cut tissue and break up kidney stones.",
 sci:"Has the highest magnetic moment of any element; concentrates magnetic fields.",
 eng:"Medical/dental lasers and high-field magnet pole pieces.",
 cos:"A neutron-capture element."},
"Er":{nat:"Natural rare earth.",use:"Fiber-optic amplifiers, lasers.",
 ov:"The rare earth that keeps the internet running.",
 bio:"Er:YAG lasers resurface skin and prepare teeth.",
 sci:"Erbium-doped fiber amplifiers boost light signals without converting them to electricity.",
 eng:"The backbone amplifiers of fiber-optic networks, plus pink glaze and lasers.",
 cos:"A neutron-capture element."},
"Yb":{nat:"Natural rare earth.",use:"Atomic clocks, fiber lasers.",
 ov:"A rare earth pushing the next generation of clocks.",
 bio:"No natural role.",
 sci:"Ytterbium optical-lattice clocks are among the most precise timekeepers ever built.",
 eng:"High-power fiber lasers for cutting and welding, and stress gauges.",
 cos:"A neutron-capture element."},
"Lu":{nat:"Natural rare earth, the heaviest.",use:"Cancer therapy, PET detectors.",
 ov:"The last and densest of the lanthanides.",
 bio:"Lutetium-177 (e.g., Lu-177 PSMA) delivers targeted radiation to prostate and neuroendocrine tumors.",
 sci:"LSO/LYSO crystals containing lutetium are fast scintillators for PET scanners.",
 eng:"Targeted radiotherapy and medical-imaging detectors.",
 cos:"A neutron-capture element."},
"W":{nat:"Natural.",use:"Filaments, cutting tools, weights.",
 ov:"'Heavy stone' - the highest melting point of any metal.",
 bio:"A few bacteria use tungsten enzymes; no human requirement.",
 sci:"Melts at 3422°C - the classic incandescent filament.",
 eng:"Tungsten-carbide cutting tools and drill bits, heat-resistant parts, weights, and electrodes.",
 cos:"A neutron-capture element."},
"Re":{nat:"Natural, one of the rarest.",use:"Jet engines, catalysis.",
 ov:"One of the last stable elements discovered, and one of the densest.",
 bio:"Rhenium-188 is used in some radiotherapies.",
 sci:"Very high melting point; strengthens superalloys.",
 eng:"Single-crystal turbine blades in jet engines and petroleum-reforming catalysts.",
 cos:"A neutron-capture element."},
"Os":{nat:"Natural.",use:"Hard-wearing tips, alloys.",
 ov:"The densest naturally occurring element.",
 bio:"Osmium tetroxide stains fat for microscopy - and is toxic and volatile.",
 sci:"Densest element and extremely hard.",
 eng:"Fountain-pen tips, instrument pivots, and durable electrical contacts.",
 cos:"A platinum-group neutron-capture element."},
"Ir":{nat:"Natural, rare.",use:"Spark plugs, crucibles, science.",
 ov:"The most corrosion-resistant metal - and a fingerprint of the dinosaurs' end.",
 bio:"No biological role; some iridium complexes are studied in cancer and imaging.",
 sci:"A worldwide iridium-rich clay layer marks the asteroid impact that ended the dinosaurs.",
 eng:"Long-life spark plugs, high-temperature crucibles, and standard-weight alloys.",
 cos:"A platinum-group element concentrated in asteroids - hence the impact layer."},
"Hg":{nat:"Natural; found native.",use:"(declining) instruments, lighting.",
 ov:"The only metal that is liquid at room temperature.",
 bio:"A potent neurotoxin; methylmercury bioaccumulates in fish (Minamata disease).",
 sci:"A dense liquid metal with high surface tension; its vapor conducts UV.",
 eng:"Historically thermometers and fluorescent lamps - now being phased out under the Minamata Convention.",
 cos:"A heavy neutron-capture element."},
"Tl":{nat:"Natural, trace.",use:"Electronics; historically poison.",
 ov:"'The poisoner's poison' - once colorless, tasteless, and deadly.",
 bio:"Highly toxic (it mimics potassium); thallium-201 was used in cardiac imaging.",
 sci:"Low-melting; used in infrared optics and detectors.",
 eng:"Electronics and infrared devices; its rat-poison use is banned.",
 cos:"A neutron-capture element."},
"Pb":{nat:"Natural; from galena.",use:"Batteries, radiation shielding.",
 ov:"Dense, soft, and a notorious cumulative poison.",
 bio:"No role; it damages the nervous system (especially in children) by mimicking calcium - now banned from fuel and paint.",
 sci:"Very dense and a strong radiation absorber; the stable endpoint of several decay chains.",
 eng:"Lead-acid car batteries and radiation shielding; historically pipes, paint, and fuel.",
 cos:"The final, stable product of uranium and thorium decay."},
"Bi":{nat:"Natural.",use:"Stomach remedies, low-melting alloys.",
 ov:"A heavy metal that is surprisingly benign - and stunning when crystallized.",
 bio:"Bismuth subsalicylate is Pepto-Bismol; it treats ulcers (with antibiotics) and diarrhea.",
 sci:"Long thought the heaviest stable element - it is barely radioactive, with a half-life far longer than the age of the universe.",
 eng:"Fusible safety alloys (fire sprinklers), lead-free solder and shot, and cosmetics.",
 cos:"A neutron-capture element."},
"Po":{nat:"Natural ultra-trace; mostly synthetic.",use:"Heat sources, anti-static.",
 ov:"So intensely radioactive that a speck glows with its own heat.",
 bio:"Extremely toxic by alpha radiation (the Litvinenko poisoning).",
 sci:"Discovered by the Curies; a single gram emits roughly 140 watts of heat.",
 eng:"Thermoelectric heat sources and anti-static brushes.",
 cos:"A short-lived decay product in uranium chains."},
"Rn":{nat:"Natural radioactive gas.",use:"(hazard) the focus is detection.",
 ov:"A radioactive noble gas that seeps up from the ground.",
 bio:"The second-leading cause of lung cancer after smoking; it pools in basements.",
 sci:"The heaviest noble gas, produced by radium and uranium decay in rock.",
 eng:"No real use - homes are tested and mitigated for it.",
 cos:"Continuously regenerated by uranium decay in the crust."},
"Ra":{nat:"Natural trace; radioactive.",use:"(historical) luminous paint.",
 ov:"The glowing element that taught the world radiation's dangers.",
 bio:"Bone-seeking and dangerous; radium-223 now treats bone metastases.",
 sci:"Discovered by the Curies; gram-for-gram about a million times more radioactive than uranium.",
 eng:"Once in glow-in-the-dark dials - the tragedy of the 'Radium Girls' - now obsolete.",
 cos:"A decay product of uranium in the crust."},
"Th":{nat:"Natural; more abundant than uranium.",use:"Potential nuclear fuel, optics.",
 ov:"A weakly radioactive metal and a possible future fuel.",
 bio:"No role; radiotoxic if inhaled or ingested.",
 sci:"'Fertile' - it breeds fissile uranium-233.",
 eng:"Proposed thorium reactors; historically gas mantles and high-index glass.",
 cos:"An r-process element whose decay helps heat Earth's interior."},
"U":{nat:"Natural; the heaviest primordial element.",use:"Nuclear power and weapons.",
 ov:"The element that splits to power cities - and to destroy them.",
 bio:"Chemically toxic to the kidneys and weakly radioactive.",
 sci:"Uranium-235 sustains a fission chain reaction; nuclear fission was discovered in 1938.",
 eng:"Reactors and weapons; depleted uranium in armor and ammunition; once colored 'Vaseline' glass.",
 cos:"Forged in neutron-star mergers; its decay drives Earth's internal heat and radiometric clocks."},
"Np":{nat:"Synthetic (trace natural).",use:"Research; plutonium production.",
 ov:"The first transuranium element, just beyond uranium.",
 bio:"Radiotoxic; no role.",
 sci:"A stepping stone in the production of plutonium.",
 eng:"Precursor to Pu-238 and used in neutron-detection research.",
 cos:"Only fleeting natural traces exist; essentially man-made."},
"Pu":{nat:"Synthetic (trace natural).",use:"Weapons, deep-space power.",
 ov:"The element that powers spacecraft - and bombs.",
 bio:"Highly radiotoxic, especially if inhaled.",
 sci:"Plutonium-239 is fissile; plutonium-238 is a steady, long-lived heat source.",
 eng:"RTGs powered by Pu-238 run Voyager, Curiosity, and New Horizons; Pu-239 fuels weapons.",
 cos:"Trace natural Pu exists; nearly all is human-made."},
"Am":{nat:"Synthetic.",use:"Smoke detectors.",
 ov:"The radioactive element quietly working in your ceiling.",
 bio:"Radiotoxic; no role.",
 sci:"Americium-241 emits alpha particles that ionize the air in a detector.",
 eng:"Ionization smoke detectors and industrial measuring gauges.",
 cos:"Entirely human-made."},
"Sc":{nat:"Natural but thinly spread.",use:"Aerospace alloys, lighting.",
 ov:"A light transition metal Mendeleev predicted before it was found ('eka-boron').",
 bio:"No biological role.",
 sci:"Scandium-aluminium alloys are strong and light; its iodide brightens stadium lamps.",
 eng:"High-performance bike frames and aerospace parts, and metal-halide lighting.",
 cos:"Made in stellar burning, but stays rare and dispersed."},
"Ti":{nat:"Natural; ninth-most abundant crustal element.",use:"Implants, aerospace, white pigment.",
 ov:"As strong as steel, nearly half the weight, and friendly to the body.",
 bio:"Biocompatible and inert - the metal of choice for joint replacements and dental implants, which bone bonds to directly.",
 sci:"Excellent strength-to-weight ratio and corrosion resistance; titanium dioxide is a brilliant white.",
 eng:"Jet engines and airframes, implants, and TiO₂ pigment in paint, sunscreen, and food.",
 cos:"Forged in stellar burning and supernovae."},
"V":{nat:"Natural.",use:"Tough steel, grid batteries.",
 ov:"A metal that makes steel tougher and may help store the grid's energy.",
 bio:"Essential to some marine organisms and a trace player in mammals; vanadium compounds mimic insulin in research.",
 sci:"Cycles through several brightly colored oxidation states.",
 eng:"High-strength tool and spring steel, and vanadium-redox-flow batteries for large-scale storage.",
 cos:"Produced in stellar silicon burning."},
"Y":{nat:"Natural rare-earth companion.",use:"Superconductors, phosphors, therapy.",
 ov:"From the Swedish village (Ytterby) that named four elements.",
 bio:"Yttrium-90 microspheres deliver targeted radiation to liver tumors.",
 sci:"A key ingredient of the YBCO high-temperature superconductor.",
 eng:"Red phosphors, LED and laser hosts (YAG), and superconductors.",
 cos:"An s-process neutron-capture element."},
"Nb":{nat:"Natural.",use:"Superconducting magnets, strong steel.",
 ov:"The metal that makes MRI and particle physics possible.",
 bio:"Biocompatible; used in some implants and jewelry.",
 sci:"Niobium-titanium is the superconducting wire in MRI machines and the Large Hadron Collider.",
 eng:"Superconducting magnets, micro-alloyed high-strength steel, and capacitors.",
 cos:"A neutron-capture element."},
"Rh":{nat:"Natural, extremely rare.",use:"Catalytic converters, mirrors.",
 ov:"Often the most expensive precious metal of all.",
 bio:"No biological role.",
 sci:"An outstanding catalyst, especially for breaking down nitrogen oxides.",
 eng:"The NOx-reducing catalyst in three-way converters, plus bright reflective plating.",
 cos:"A platinum-group neutron-capture element."},
"Hf":{nat:"Natural; travels with zirconium.",use:"Reactor control, computer chips.",
 ov:"Zirconium's near-twin, but with the opposite nuclear appetite.",
 bio:"No biological role.",
 sci:"A voracious neutron absorber (unlike zirconium) and a high-κ gate insulator.",
 eng:"Nuclear control rods, transistor gate dielectrics, and superalloys.",
 cos:"A neutron-capture element."},
"Ta":{nat:"Natural; from coltan ore.",use:"Capacitors, implants.",
 ov:"The capacitor metal inside nearly every phone.",
 bio:"Inert and biocompatible - used in implants and surgical mesh.",
 sci:"Forms a stable oxide ideal for tiny, high-capacity capacitors; very high melting point.",
 eng:"Compact electronics capacitors, chemical equipment, and medical implants.",
 cos:"A neutron-capture element (its rarest isotope is among the rarest in nature)."},
"Pt":{nat:"Natural; found native, very rare.",use:"Chemotherapy, catalysis, electrodes.",
 ov:"A precious, almost unreactive metal that also fights cancer.",
 bio:"Cisplatin and related platinum drugs cross-link DNA to kill cancer cells - among the most widely used chemotherapies.",
 sci:"An exceptional catalyst and one of the least reactive metals.",
 eng:"Catalytic converters, fuel-cell electrodes, lab ware, and jewelry.",
 cos:"A platinum-group element forged by neutron capture, including neutron-star mergers."},
"Tm":{nat:"Natural rare earth, the rarest stable lanthanide.",use:"Portable X-rays, lasers.",
 ov:"A scarce rare earth named for the mythic far north (Thule).",
 bio:"No natural role.",
 sci:"Thulium-170 emits X-rays usable in compact, power-free imaging sources.",
 eng:"Portable X-ray devices and thulium lasers for surgery.",
 cos:"A neutron-capture element."},
"Pm":{nat:"Synthetic; essentially absent in nature.",use:"Luminous paint, nuclear batteries.",
 ov:"The only radioactive lanthanide - fittingly named for Prometheus.",
 bio:"Radiotoxic; no role.",
 sci:"Its beta decay can power tiny long-lived batteries and excite phosphors.",
 eng:"Glow-in-the-dark signage and miniature nuclear batteries.",
 cos:"Made in supernovae and reactors, but decays away - none survives in Earth's rocks."},
"At":{nat:"Natural ultra-trace; the rarest naturally occurring element.",use:"Targeted cancer therapy (research).",
 ov:"So rare that less than a gram exists in Earth's crust at any moment.",
 bio:"Astatine-211 is a promising alpha-emitter for targeted radiotherapy.",
 sci:"A halogen that already behaves somewhat metallically; all isotopes are short-lived.",
 eng:"No bulk applications; studied only in trace amounts.",
 cos:"A fleeting decay product in natural uranium/thorium chains."},
"Fr":{nat:"Natural ultra-trace; intensely radioactive.",use:"Pure research only.",
 ov:"The most unstable of the first 101 elements - only a handful of atoms are studied at a time.",
 bio:"No role; too short-lived to matter biologically.",
 sci:"The most electropositive element; useful for testing atomic theory.",
 eng:"No applications.",
 cos:"A transient decay product of actinium in the crust."},
"Ac":{nat:"Natural trace; radioactive.",use:"Targeted alpha therapy (research).",
 ov:"The namesake of the actinides; it glows pale blue in the dark.",
 bio:"Actinium-225 is an emerging targeted alpha-particle cancer therapy.",
 sci:"Intensely radioactive; chemically resembles lanthanum.",
 eng:"Medical isotope research; otherwise no bulk use.",
 cos:"A decay product of uranium."},
"Pa":{nat:"Natural trace; radioactive and toxic.",use:"Marine sediment dating (research).",
 ov:"A rare, dangerous metal whose name means 'parent of actinium'.",
 bio:"Radiotoxic; no role.",
 sci:"The protactinium-thorium ratio dates ocean sediments and corals.",
 eng:"No commercial use.",
 cos:"A decay product in the uranium-235 chain."},
"Cm":{nat:"Synthetic.",use:"Spacecraft instruments, research.",
 ov:"A self-heating, self-glowing actinide named for the Curies.",
 bio:"Radiotoxic; no role.",
 sci:"A strong alpha and heat source.",
 eng:"Powers the alpha-particle X-ray spectrometers on Mars rovers.",
 cos:"Human-made; created atom-by-atom."},
"Bk":{nat:"Synthetic.",use:"Making heavier elements (research).",
 ov:"A scarce actinide named for Berkeley, California.",
 bio:"Radiotoxic; no role.",
 sci:"Produced in only microgram quantities.",
 eng:"A berkelium target was used to synthesize element 117, tennessine.",
 cos:"Entirely human-made."},
"Cf":{nat:"Synthetic.",use:"Neutron source.",
 ov:"One of the few synthetic elements with real industrial use.",
 bio:"Radiotoxic; brachytherapy research.",
 sci:"Californium-252 is a powerful, portable neutron emitter.",
 eng:"Reactor start-up sources, neutron imaging, and oil-well logging.",
 cos:"Human-made; also forged briefly in supernovae and nuclear tests."},
"Es":{nat:"Synthetic.",use:"Pure research.",
 ov:"Discovered in the fallout of the first hydrogen-bomb test.",
 bio:"Radiotoxic; no role.",
 sci:"Made in tiny amounts; used to study actinide chemistry and make heavier elements.",
 eng:"No applications.",
 cos:"Human-made."},
"Fm":{nat:"Synthetic.",use:"Pure research.",
 ov:"The heaviest element that can be made by neutron capture in a reactor.",
 bio:"No role.",
 sci:"Studied only as individual atoms.",
 eng:"No applications.",
 cos:"Human-made; also appears briefly in nuclear explosions."},
"Md":{nat:"Synthetic.",use:"Pure research.",
 ov:"Named for Mendeleev, the architect of the periodic table.",
 bio:"No role.",
 sci:"Made and studied one atom at a time.",
 eng:"No applications.",
 cos:"Human-made."},
"No":{nat:"Synthetic.",use:"Pure research.",
 ov:"An actinide named for Alfred Nobel.",
 bio:"No role.",
 sci:"Unusually stable in the +2 state - a clue to relativistic effects.",
 eng:"No applications.",
 cos:"Human-made."},
"Lr":{nat:"Synthetic.",use:"Pure research.",
 ov:"The last of the actinides, named for cyclotron inventor E. Lawrence.",
 bio:"No role.",
 sci:"Its electron configuration probes how relativity reshapes heavy atoms.",
 eng:"No applications.",
 cos:"Human-made."},
"Rf":{nat:"Synthetic.",use:"Pure research.",
 ov:"The first transactinide, expected to behave like hafnium.",
 bio:"No role.",
 sci:"Chemistry studied atom-by-atom to test periodic trends.",
 eng:"No applications.",
 cos:"Created in particle accelerators."},
"Db":{nat:"Synthetic.",use:"Pure research.",
 ov:"A superheavy element named for the Dubna laboratory in Russia.",
 bio:"No role.",
 sci:"Predicted to resemble tantalum; studied a few atoms at a time.",
 eng:"No applications.",
 cos:"Created in particle accelerators."},
"Sg":{nat:"Synthetic.",use:"Pure research.",
 ov:"One of the few elements named for a person who was still living (Glenn Seaborg).",
 bio:"No role.",
 sci:"Chemistry experiments suggest it behaves like tungsten.",
 eng:"No applications.",
 cos:"Created in particle accelerators."},
"Bh":{nat:"Synthetic.",use:"Pure research.",
 ov:"A superheavy element named for Niels Bohr.",
 bio:"No role.",
 sci:"Behaves chemically like its lighter relative rhenium.",
 eng:"No applications.",
 cos:"Created in particle accelerators."},
"Hs":{nat:"Synthetic.",use:"Pure research.",
 ov:"Named for the German state of Hesse.",
 bio:"No role.",
 sci:"Forms a volatile oxide, just as osmium does - a periodic-table success story.",
 eng:"No applications.",
 cos:"Created in particle accelerators."},
"Mt":{nat:"Synthetic.",use:"Pure research.",
 ov:"Named for physicist Lise Meitner, who explained nuclear fission.",
 bio:"No role.",
 sci:"Properties are predicted, not yet measured - too few atoms, too short-lived.",
 eng:"No applications.",
 cos:"Created in particle accelerators."},
"Ds":{nat:"Synthetic.",use:"Pure research.",
 ov:"Named for Darmstadt, Germany, where it was made.",
 bio:"No role.",
 sci:"Only a handful of atoms have ever existed; properties are theoretical.",
 eng:"No applications.",
 cos:"Created in particle accelerators."},
"Rg":{nat:"Synthetic.",use:"Pure research.",
 ov:"Named for Wilhelm Röntgen, discoverer of X-rays.",
 bio:"No role.",
 sci:"Predicted to be a noble-metal-like member of the gold group.",
 eng:"No applications.",
 cos:"Created in particle accelerators."},
"Cn":{nat:"Synthetic.",use:"Pure research.",
 ov:"Named for Copernicus; relativity may make it behave very oddly.",
 bio:"No role.",
 sci:"Predicted to be extremely volatile - possibly a gas or liquid-like metal.",
 eng:"No applications.",
 cos:"Created in particle accelerators."},
"Nh":{nat:"Synthetic.",use:"Pure research.",
 ov:"The first element discovered in Asia (Japan, 'Nihon').",
 bio:"No role.",
 sci:"Decays within seconds; properties largely predicted.",
 eng:"No applications.",
 cos:"Created in particle accelerators."},
"Fl":{nat:"Synthetic.",use:"Pure research.",
 ov:"Named for physicist Georgy Flerov; sits near the predicted 'island of stability'.",
 bio:"No role.",
 sci:"Its volatility is studied to see whether it behaves like a metal or a noble gas.",
 eng:"No applications.",
 cos:"Created in particle accelerators."},
"Mc":{nat:"Synthetic.",use:"Pure research.",
 ov:"Named for Moscow; only a few atoms have been made.",
 bio:"No role.",
 sci:"Decays in a fraction of a second into other superheavy elements.",
 eng:"No applications.",
 cos:"Created in particle accelerators."},
"Lv":{nat:"Synthetic.",use:"Pure research.",
 ov:"Named for the Lawrence Livermore National Laboratory.",
 bio:"No role.",
 sci:"Extremely short-lived; properties are predicted from periodic trends.",
 eng:"No applications.",
 cos:"Created in particle accelerators."},
"Ts":{nat:"Synthetic.",use:"Pure research.",
 ov:"The second-heaviest element, named for Tennessee.",
 bio:"No role.",
 sci:"In the halogen column, but predicted to behave more like a metal.",
 eng:"No applications.",
 cos:"Made using a berkelium target in a particle accelerator."},
"Og":{nat:"Synthetic.",use:"Pure research.",
 ov:"The heaviest known element, named for living physicist Yuri Oganessian.",
 bio:"No role.",
 sci:"Sits in the noble-gas column, but relativity is predicted to make it reactive - and possibly solid, not a gas.",
 eng:"No applications.",
 cos:"Only a few atoms have ever been created in the lab."}
};



