/* Rich deep-dive content for high-yield elements. Others fall back to a
   computed atom + category overview. Fields: nat, use, ov, bio, sci, eng, cos */
window.PT_DEEP={
"H":{nat:"Most abundant element in the universe (~75% of normal matter).",use:"Fuel, ammonia synthesis, pH.",
 ov:"The simplest atom — one proton, one electron — and the building block from which the stars made everything else.",
 bio:"As the H⁺ ion it sets pH; the hydrogen-ion gradient across the inner mitochondrial membrane is what ATP synthase converts into ATP. Hydrogen bonds hold DNA's strands and fold every protein.",
 sci:"Its single electron gives the cleanest spectral lines in physics (the Balmer series) and made hydrogen the test-bed for quantum theory. Deuterium and tritium are its heavy isotopes.",
 eng:"Hydrogen fuel cells turn H₂ + O₂ into electricity and water; the Haber–Bosch process fixes it into ammonia, feeding roughly half the planet.",
 cos:"Fusion of hydrogen into helium powers the Sun and every main-sequence star — the original energy source behind nearly all life."},
"He":{nat:"Second-most abundant element; on Earth it's collected from natural gas.",use:"Cryogenics, MRI, lift.",
 ov:"A noble gas so unreactive it forms essentially no compounds, and so light it escapes Earth's gravity.",
 bio:"Biologically inert, but breathed in heliox mixes to help patients move air through narrowed airways, and by divers to avoid nitrogen narcosis.",
 sci:"Liquid helium (4 K) is the coldest common coolant and becomes a frictionless superfluid; it cools the superconducting magnets at the heart of physics.",
 eng:"Indispensable for MRI magnets, semiconductor manufacturing, and leak detection — a finite, non-renewable resource once it's released.",
 cos:"Forged in the Big Bang and in stellar cores; first detected in the Sun's spectrum before it was ever found on Earth."},
"C":{nat:"Natural; the structural backbone of all known life.",use:"Organic chemistry, steel, materials.",
 ov:"The element of life: four bonds, endless architectures — chains, rings, sheets, cages.",
 bio:"Every biomolecule — carbohydrate, lipid, protein, nucleic acid — is a carbon skeleton. The carbon cycle moves it between CO₂, living tissue, and rock.",
 sci:"Its bonding versatility founds all of organic chemistry; radiocarbon (¹⁴C) dating reads the clock of decay; allotropes range from diamond to graphite to graphene.",
 eng:"Carbon fiber and steel (iron + carbon) build the modern world; graphene and nanotubes are the frontier of materials science.",
 cos:"Made in dying stars and seeded across the galaxy — the cosmos is, chemically, a carbon story."},
"N":{nat:"78% of the air you breathe.",use:"Fertilizer, proteins, inert atmospheres.",
 ov:"An atmosphere of it surrounds us, yet life can't use it until it's 'fixed' into a reactive form.",
 bio:"Nitrogen is in every amino acid and nucleotide. Biological nitrogen fixation by bacteria, and industrial fixation by humans, gate how much life a system can support.",
 sci:"The triple bond in N₂ is one of the strongest in chemistry, which is why it's so inert; liquid nitrogen (77 K) is a workhorse coolant.",
 eng:"The Haber–Bosch process converts N₂ to ammonia for fertilizer; nitrogen blankets protect food and electronics from oxidation.",
 cos:"A major product of stellar nucleosynthesis and a key component of many planetary atmospheres."},
"O":{nat:"~21% of air; most abundant element in Earth's crust.",use:"Respiration, combustion, oxides.",
 ov:"The element that made complex life possible — and the one that lets it burn fuel for energy.",
 bio:"The final electron acceptor in cellular respiration; without O₂ at the end of the chain, ATP production collapses. It's carried by hemoglobin's iron.",
 sci:"A potent oxidizer; its discovery overturned the phlogiston theory and founded modern chemistry. Ozone (O₃) shields the surface from UV.",
 eng:"Drives steelmaking, combustion, and medical oxygen; liquid oxygen is a rocket oxidizer.",
 cos:"Built in massive stars; the Great Oxidation Event reshaped Earth's atmosphere ~2.4 billion years ago."},
"F":{nat:"Natural but always combined; the most reactive nonmetal.",use:"Toothpaste, Teflon, etching.",
 ov:"The most electronegative element — it grabs electrons from almost anything.",
 bio:"Trace fluoride hardens tooth enamel into fluorapatite, reducing decay; in excess it's toxic.",
 sci:"So reactive it even attacks glass and was isolated only after decades of dangerous attempts (Moissan, 1886).",
 eng:"Builds PTFE (Teflon), refrigerants, and the etchants and high-κ layers of semiconductor fabrication.",
 cos:"Relatively rare cosmically because stellar processes readily destroy it."},
"Na":{nat:"Natural, always as a salt; abundant in seawater.",use:"Nerve signaling, salt, lamps.",
 ov:"A soft metal so reactive it bursts into flame on water — yet half of table salt.",
 bio:"The Na⁺/K⁺-ATPase pumps sodium out of every cell, setting the gradient that fires neurons and muscle and drives nutrient absorption.",
 sci:"Its bright yellow emission line is a classic flame-test and the glow of street lamps.",
 eng:"Molten sodium cools fast nuclear reactors; sodium-ion batteries are an emerging cheap alternative to lithium.",
 cos:"Forged in stars; its D-lines are among the most studied features in astronomical spectra."},
"Mg":{nat:"Natural; eighth-most abundant element in the crust.",use:"Enzymes, alloys, chlorophyll.",
 ov:"A light structural metal and a quiet workhorse of biochemistry.",
 bio:"A cofactor for hundreds of enzymes — every reaction that uses ATP actually uses Mg·ATP — and the atom at the center of chlorophyll.",
 sci:"Burns with a brilliant white light; a strong reducing agent used to win other metals from their oxides.",
 eng:"Magnesium alloys are among the lightest structural metals, used in aerospace and automotive parts.",
 cos:"A common product of stellar carbon and neon burning."},
"Al":{nat:"Most abundant metal in the crust (as bauxite).",use:"Packaging, aircraft, wiring.",
 ov:"Once more precious than gold, now the everyday light metal — because electricity unlocked it.",
 bio:"No biological role; high exposure is neurotoxic, so the body largely excludes it.",
 sci:"Forms a self-healing oxide layer that resists corrosion; extracted by the energy-hungry Hall–Héroult electrolysis.",
 eng:"Strong-yet-light alloys build aircraft, cars, cans, and power lines; endlessly recyclable for a fraction of the smelting energy.",
 cos:"²⁶Al, a radioactive isotope, heated the earliest planetesimals in the young solar system."},
"Si":{nat:"Second-most abundant crustal element (as silicates).",use:"Chips, glass, solar cells.",
 ov:"The rock beneath our feet and the brain inside our machines.",
 bio:"Trace roles in connective tissue and in the silica skeletons of diatoms and grasses.",
 sci:"A metalloid semiconductor whose conductivity can be precisely tuned by doping — the basis of all modern electronics.",
 eng:"Ultra-pure silicon crystals are sliced into the wafers of every computer chip and most solar panels.",
 cos:"A major rock-forming element across the terrestrial planets."},
"P":{nat:"Natural, always combined (phosphates).",use:"DNA, ATP, fertilizer.",
 ov:"The element of energy and information in the cell.",
 bio:"Phosphate is the backbone of DNA and RNA, the 'currency' bonds of ATP, and the on/off switch of protein phosphorylation; it's also bone mineral.",
 sci:"White phosphorus glows and ignites in air; its discovery (from urine, 1669) was the first by a known person.",
 eng:"Phosphate fertilizer underpins modern agriculture — and is a finite, mined resource.",
 cos:"Comparatively scarce in the cosmos, which makes its central role in biochemistry striking."},
"S":{nat:"Natural; found native near volcanoes.",use:"Proteins, sulfuric acid, vulcanization.",
 ov:"The yellow element of brimstone and of the bonds that hold proteins in shape.",
 bio:"In the amino acids cysteine and methionine; disulfide bridges lock protein and antibody structure; part of several vitamins and cofactors.",
 sci:"Sulfuric acid is the most-produced industrial chemical and a rough index of an economy's output.",
 eng:"Vulcanization with sulfur turns soft rubber into tires; sulfur is central to fertilizers and refining.",
 cos:"Produced in stellar oxygen burning and spread by supernovae."},
"Cl":{nat:"Natural, always combined; abundant in seawater.",use:"Disinfection, salt, PVC.",
 ov:"A poison gas that, tamed as the chloride ion, is essential to life.",
 bio:"The major extracellular anion; balances charge, drives the chloride shift in red cells, and is secreted as stomach acid (HCl).",
 sci:"A strong oxidizer and the classic example of an electronegative halogen forming ionic salts with metals.",
 eng:"Chlorination made drinking water safe — a public-health milestone; it also makes PVC and countless solvents.",
 cos:"Forged in stars; detected in interstellar clouds as HCl and other molecules."},
"K":{nat:"Natural; seventh-most abundant crustal element.",use:"Nerve signaling, fertilizer.",
 ov:"The dominant ion inside your cells, and the counterpart to sodium in every nerve impulse.",
 bio:"The main intracellular cation; the K⁺ gradient sets the resting membrane potential, and its efflux repolarizes neurons and the heart. Potassium swings are acutely cardiac-dangerous.",
 sci:"A soft, violently water-reactive alkali metal with a lilac flame; ⁴⁰K is a natural radioactive clock for dating rocks.",
 eng:"Potash is one of the three primary fertilizer nutrients (the 'K' in N-P-K).",
 cos:"Made in stars; ⁴⁰K contributes to Earth's internal radioactive heat."},
"Ca":{nat:"Natural; fifth-most abundant crustal element.",use:"Bone, signaling, cement.",
 ov:"Structure and signal at once — it builds the skeleton and triggers the cell.",
 bio:"Hydroxyapatite gives bone and teeth their hardness; as a tightly controlled second messenger, Ca²⁺ triggers muscle contraction, neurotransmitter release, and clotting.",
 sci:"A reactive alkaline-earth metal; its carbonate (limestone) and sulfate (gypsum) shape geology and construction.",
 eng:"Limestone and lime are the backbone of cement, steel, and glass making.",
 cos:"A product of stellar oxygen and silicon burning; common in rocky bodies."},
"Fe":{nat:"Natural; most of Earth's core, fourth in the crust.",use:"Steel, hemoglobin, magnets.",
 ov:"The metal that built civilization and the atom that carries your oxygen.",
 bio:"At the center of heme, iron binds O₂ in hemoglobin and shuttles electrons in the respiratory chain; deficiency causes anemia, overload damages organs.",
 sci:"Iron has the most stable nucleus, so fusion stops there — the endpoint of stellar energy production. It's strongly ferromagnetic.",
 eng:"Iron + carbon = steel, the dominant structural material of the modern world.",
 cos:"The last element a massive star can fuse for energy; its build-up triggers core collapse and supernova."},
"Cu":{nat:"Natural; sometimes found native.",use:"Wiring, enzymes, alloys.",
 ov:"The first metal humans worked, and still the wire that carries our power.",
 bio:"A cofactor in enzymes for energy production and iron handling (e.g., cytochrome c oxidase); deficiency and overload (Wilson's disease) both cause disease.",
 sci:"Second only to silver in electrical conductivity; its salts are famously blue-green.",
 eng:"The default conductor for wiring and motors; bronze (Cu+Sn) and brass (Cu+Zn) are foundational alloys.",
 cos:"Synthesized in massive stars and supernovae."},
"Zn":{nat:"Natural, always combined.",use:"Enzymes, galvanizing, immunity.",
 ov:"A quiet but essential trace metal — in hundreds of proteins and on every galvanized surface.",
 bio:"A structural and catalytic cofactor in 300+ enzymes and in 'zinc-finger' DNA-binding proteins; vital for immunity, healing, and taste.",
 sci:"A reactive metal that readily gives up electrons — which is exactly why it protects iron.",
 eng:"Galvanizing coats steel in zinc as a sacrificial anode against rust; the negative electrode of many batteries.",
 cos:"Produced in stars and dispersed by stellar death."},
"I":{nat:"Natural, concentrated in seawater and seaweed.",use:"Thyroid hormone, antiseptic, contrast.",
 ov:"A trace halogen with an outsized job: it runs your metabolism.",
 bio:"The thyroid uses iodine to build T₃ and T₄, the hormones that set metabolic rate; deficiency causes goiter and, in development, cretinism — which iodized salt prevents.",
 sci:"A purple-vapor halogen; its heavy nucleus makes it useful as an X-ray/CT contrast agent.",
 eng:"Iodine disinfectants, and radioactive ¹³¹I to image and treat the thyroid.",
 cos:"A heavy element built largely by neutron capture in stellar and supernova environments."},
"Au":{nat:"Natural; found native as the metal.",use:"Currency, electronics, medicine.",
 ov:"Prized for not changing — the metal that never tarnishes.",
 bio:"Largely inert in the body; gold compounds have been used for rheumatoid arthritis and gold nanoparticles are emerging in diagnostics and targeted therapy.",
 sci:"Extremely unreactive and an excellent conductor; relativistic effects on its electrons give gold its yellow color.",
 eng:"Corrosion-proof contacts and bonding wires in electronics; reflective coatings on spacecraft and visors.",
 cos:"Forged in the most violent events in the universe — neutron-star collisions."}
};
